#订单中心服务端口
#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/dubbo_order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false"
    username: root
    password: jimuchen
#dubbo配置
dubbo:
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.moses.order.provider
  config-center:
    timeout: 10000
  application:
    id: du-order
    name: du-order
  consumer:
    timeout: 10000
    retries: 0
  protocol:
    port: 20881
    name: dubbo
  registry:
    protocol: zookeeper
    #zookeeper注册中心地址
    address: zookeeper://192.168.50.201:2181?backup=192.168.50.202:2181,192.168.50.203:2181
