server:
  port: 80

dubbo:
  config-center:
    timeout: 10000
  application:
    id: du-customer-web
    name: du-customer-web
  consumer:
    timeout: 10000
    retries: 0
    check: false
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.moses.web
  protocol:
    port: 20882
    name: dubbo
  registry:
    protocol: zookeeper
    #zookeeper注册中心地址
    address: zookeeper://${ZK_SERVER}:2181